In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("/content/i1.csv")

In [ ]:
df.head()

,Date,Timestamp,Invoice No.,Item Name,Price,Qty.,Sub Total,Discount,Tax,Final Total,Table No.,Server Name,Covers,Variation,Category,HSN
0,2023-09-19,2023-09-19 22:03:44,28389,Kulcha,55.0,1.0,55.0,0.0,2.76,57.76,16,biller,0,NaN,Indian Breads,NaN
1,2023-09-19,2023-09-19 22:03:44,28389,Parota,30.0,4.0,120.0,0.0,6.00,126.00,16,biller,0,NaN,Indian Breads,NaN
2,2023-09-19,2023-09-19 22:03:44,28389,Mushroom Masala,150.0,1.0,150.0,0.0,7.50,157.50,16,biller,0,NaN,Veg Gravy,NaN
3,2023-09-19,2023-09-19 22:03:44,28389,Paneer Butter Masala,150.0,1.0,150.0,0.0,7.50,157.50,16,biller,0,NaN,Veg Gravy,NaN
4,2023-09-19,2023-09-19 22:03:44,28389,Gobi- 65,120.0,1.0,120.0,0.0,6.00,126.00,16,biller,0,NaN,Veg Starters,NaN

In [ ]:
df.tail()

,Date,Timestamp,Invoice No.,Item Name,Price,Qty.,Sub Total,Discount,Tax,Final Total,Table No.,Server Name,Covers,Variation,Category,HSN
7237,2023-07-01,2023-07-01 15:17:24,26194,Lemon Soda,50.0,1.0,50.0,0.0,2.5,52.5,3,biller,0,NaN,Deserts & Mocktails,NaN
7238,2023-07-01,2023-07-01 15:17:24,26194,Mineral Water,20.0,1.0,20.0,0.0,1.0,21.0,3,biller,0,NaN,Deserts & Mocktails,NaN
7239,2023-07-01,2023-07-01 13:12:54,26193,Lemon Soda,50.0,3.0,150.0,0.0,7.5,157.5,10,biller,0,NaN,Deserts & Mocktails,NaN
7240,2023-07-01,2023-07-01 13:08:33,26192,Oreo Milk Shake,120.0,1.0,120.0,0.0,6.0,126.0,4,biller,0,NaN,Deserts & Mocktails,NaN
7241,2023-07-01,2023-07-01 13:07:17,26191,Chicken Biriyani With Raitha And Gravy,160.0,2.0,320.0,0.0,16.0,336.0,2,biller,0,NaN,NON VEG BRIYANI & RICE,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7242 entries, 0 to 7241
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         7242 non-null   object
 1   Timestamp    7242 non-null   object
 2   Invoice No.  7242 non-null   int64
 3   Item Name    7242 non-null   object
 4   Price        7242 non-null   float64
 5   Qty.         7242 non-null   float64
 6   Sub Total    7242 non-null   float64
 7   Discount     7242 non-null   float64
 8   Tax          7242 non-null   float64
 9   Final Total  7242 non-null   float64
 10  Table No.    7242 non-null   int64
 11  Server Name  7242 non-null   object
 12  Covers       7242 non-null   int64
 13  Variation    8 non-null      object
 14  Category     7242 non-null   object
 15  HSN          0 non-null      float64
dtypes: float64(7), int64(3), object(6)
memory usage: 905.4+ KB

In [ ]:
df.describe()

,Invoice No.,Price,Qty.,Sub Total,Discount,Tax,Final Total,Table No.,Covers,HSN
count,7242.000000,7242.000000,7242.000000,7242.000000,7242.000000,7242.000000,7242.000000,7242.000000,7242.0,0.0
mean,27333.419497,122.911627,1.375725,160.320768,1.441421,7.944264,166.823611,20.137255,0.0,NaN
std,613.515739,61.393453,0.948374,134.136442,6.649815,6.662533,139.913793,18.124931,0.0,NaN
min,26191.000000,20.000000,1.000000,20.000000,0.000000,0.900000,18.900000,1.000000,0.0,NaN
25%,26822.000000,60.000000,1.000000,100.000000,0.000000,4.960000,103.960000,5.000000,0.0,NaN
50%,27356.000000,140.000000,1.000000,160.000000,0.000000,7.500000,157.500000,13.000000,0.0,NaN
75%,27829.000000,160.000000,1.000000,170.000000,0.000000,8.500000,178.500000,41.000000,0.0,NaN
max,28389.000000,399.000000,19.000000,3781.000000,288.000000,189.060000,3970.060000,50.000000,0.0,NaN

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Invoice No.,7242.0,27333.419497,613.515739,26191.0,26822.00,27356.0,27829.0,28389.00
Price,7242.0,122.911627,61.393453,20.0,60.00,140.0,160.0,399.00
Qty.,7242.0,1.375725,0.948374,1.0,1.00,1.0,1.0,19.00
Sub Total,7242.0,160.320768,134.136442,20.0,100.00,160.0,170.0,3781.00
Discount,7242.0,1.441421,6.649815,0.0,0.00,0.0,0.0,288.00
Tax,7242.0,7.944264,6.662533,0.9,4.96,7.5,8.5,189.06
Final Total,7242.0,166.823611,139.913793,18.9,103.96,157.5,178.5,3970.06
Table No.,7242.0,20.137255,18.124931,1.0,5.00,13.0,41.0,50.00
Covers,7242.0,0.000000,0.000000,0.0,0.00,0.0,0.0,0.00
HSN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.shape

(7242, 16)

In [ ]:
df["Invoice No."].unique()

array([28389, 28388, 28387, ..., 26193, 26192, 26191])

In [ ]:
df["Invoice No."].nunique()

2199

In [ ]:
df["Item Name"].unique()

array(['Kulcha', 'Parota', 'Mushroom Masala', 'Paneer Butter Masala',
       'Gobi- 65', 'Mineral Water', 'Chilly Fish Dry', 'Fish 65',
       'Prawn Chilli', 'Chicken 65 Boneless', 'Chicken Lolly Pop',
       'Chicken Biriyani With Raitha And Gravy',
       'Egg Briyani With Raitha And Chicken Gravy', 'Paneer Noodles',
       'Plain Briyani With Raitha, Gravy.',
       'Schezwan Mushroom Fried Rice', 'Chicken Fried Rice',
       'Schewan Chicken Noodle', 'Schezwan Egg Fried Rice', 'Chicken 65',
       'Chicken Manchurian Dry', 'Prawn Pepper Fry',
       'Butter Chicken Gravy', 'Schezwan Chicken Gravy', 'Butter Naan',
       'Romali Roti (1 No)', 'Roti', 'Chicken Noodles', 'Naan',
       'French Fries', 'Veg Noodles', 'Pulka (2 No)', 'Kadai Paneer',
       'Pepper Garlic Chicken Soup', 'Singapore Noodles Veg',
       'Dragon Chicken', 'Chicken Chettinad Gravy', 'Butter Milk',
       'Fresh Lemon Juice', 'Veg Fried Rice', 'Pepper Chicken Gravy',
       'Prawn Fried Rice', 'Singapore Fried Rice Veg', 'Chapathi (2 No)',
       'Green Peas  Masala', 'Baby Corn 65', 'Paneer Pulao',
       'Soft Drink 600ml', 'Baby Corn Pepper Fry', 'Dragon Mushroom',
       'Hydrabadi Veg Biriyani', 'Jeera Peas Pulao', 'Lachha Paratha',
       'Garlic Roti', 'Butter Roti', 'Garlic Naan', 'Egg Noodles',
       'Chicken Tikka Masala', 'Chicken Manchurian Gravy',
       'Chicken Kheema Masala', 'Karaikudi Kozhi Kozhimbu',
       'Chilly Chicken Gravy', 'Singapore Fried Rice Non-veg',
       'Dragon Prawns', 'Chicken Kothu Paratha', 'Kozhi Milaghuperattal',
       'Egg Pepper Fry', 'Chicken Kati Roll', 'Schewan Veg Fried Rice',
       'Dragon Paneer', 'Egg Fried Rice', 'Egg Bhurji Masala',
       'Pichipotta Kozhivaruval', 'Honey Chicken', 'Aalu Gobi Masala',
       'Chicken Clear Soup', 'Schewan  Chicken Fried Rice',
       'Schezwan Chicken Dry', 'Pepper Tandoori Chicken ( Half )', 'Tea',
       'Kadai Vegetable', 'Schezwan Chicken  Fried Rice',
       'Kadai Mushroom', 'Plain Paratha (1 No)', 'Egg Kothu Paratha',
       'Green Peas  Mushroom  Masala', 'Dal Tudka', 'Dingri Mutter',
       'Hydrabadi Chicken Masala', 'Boiled Egg (2 Nos)',
       'Chicken Pallipalayam', 'Hot And Sour Chicken Soup',
       'Hot And Sour Veg Soup', 'Thandoor Chicken Half', 'Dragon Gobi',
       'Sweet Corn Veg Soup', 'Kadai Chicken', 'Masala Omelet (two Eggs',
       'Paneer- 65', 'Butter Kulcha', 'Manchow Veg Soup', 'Mushroom - 65',
       'Ghee Rice', 'Singapore Noodles Non-veg', 'Sesame Fried Chicken',
       'Egg Roll', 'Chilly Chicken Dry', 'Dragon Babycorn', 'Dhai Poori',
       'Prawn Biriyani', 'Curd Rice', 'Jeera Rice', 'Mushroom Biriyani',
       'Garlic Chicken Masasla', 'Grill Chicken (full)',
       'Paneer Fried Rice', 'Tandoori Paratha', 'Kozhicharru',
       'Honey Potato', 'Babycorn Manchurian', 'Paneer Manchurian',
       'Blue Lagoon', 'Strawberry Scoop', 'Lemon Soda', 'Chicken Roast',
       'Karaikudi Chicken', 'Mixed Fried Rice',
       'Manchurian Gravy (Mushroom)', 'Thandoor Chicken Full',
       'Paneer Do Pyaza', 'Soft Drink 250ml', 'Pepper Thandoor (quarter)',
       'Schezwan Veg Noodles', 'Egg Bhurji', 'Mushroom Manchurian',
       'Kadai Vegetables', 'Manchow Chicken Soup', 'Schewan Egg Noodle',
       'Kozhi Sukka', 'Kalaki', 'Chappathi (1 No.)', 'Prawn Manchurian',
       'Chicken Pallipalayam Gravy', 'Sweet Corn Chicken Soup',
       'Kumpo Chicken', 'Prawn 65', 'Manchurian Gravy (Gobi)',
       'Mixed Veg Pulao', 'Schezwan Paneer Fried Rice',
       'Methi Chicken Masala', 'Kozhi Malliperattal', 'Fish Finger',
       'Egg Masala', 'Schezwan Prawn Fried Rice', 'Veg Kothu Parata',
       'Gulab Jamun', 'Mushroom Pulao', 'Mixed Veg Curry',
       'Pepper Tandoori Chicken ( Full )', 'Prawn Pepper And Salt',
       'Grill Chicken ( Quater )', 'Grill Chicken (half)',
       'Channa Masala', 'Chinese Chopsey(veg)', 'Kheema Paneer',
       'Chicken Biriyani Buy 1', 'Vechhu Paratha (1 No)',
       'Ice Cream With Jamun', 'Dragon Fish', 'Mushroom Fried Rice',
       'Black Current Scoop', 'Prawn Noodles', 'Tangdi Kebab',
       'Vegetable Pepper Soup', 'Kadai Prawns', 'Bread Omblet',
       'Chilly Ladies Finger', 'Chilly Mushroom(chinese)',
       'Green Peas Pulao', 'Gobi Mushroom', 'Chilly Gobi (chinese)',
       'Potato Manchurian', 'Tawa Paratha', 'Gobi Manchurian',
       'Mixed Noodles', 'Schezwan Gobi', 'Mixed Chilly Vegetable',
       'Venilla Scoop', 'Chocolate Scoop', 'Kadai Fish', 'Chilli Paneer',
       'Bulls Eye', 'Fish Manchurian Dry', 'Tomato Soup',
       'Mint Lemon Juice', 'Butterscotch Milk Shake',
       'Chocolate Milk Shake', 'Chicken Thangdi Kebab', 'Gobi Potato',
       'Tandoor Chicken ( Quarter)', 'Schezwan Mushroom',
       'Mutton Pepper Fry', 'Butter Scotch Scoop', 'Chicken Pulao',
       'Oreo Milk Shake', 'Mint Lime Soda', 'Mutton Biriyani',
       'Peanut Masala', 'Chinese Chopsey Chicken', 'Schezwan Paneer',
       'Prawns Schezwan Noodles', 'Strawberry Milk Shake',
       'Veg Clear Soup', 'Chilly Potato', 'Venila Milk Shake', 'Mojito',
       'Hariyali Chicken Tikka', 'Aalu Mutter Masala',
       'Pepper Chicken Boneless', 'Full Boil', 'Black Current Milkshake',
       'Chettinad Mushroom Masala', 'Mushroom Gravy',
       'Pepper Jeeraga Chicken', 'Pichi Potta Kozhi Varuval',
       'Oreo Scoop', 'Nattukozhi Mallivaruval', 'Kanniyakumari Fish Fry',
       'Soft Drinks Tin',
       '1 Indian Combo - Welcome Drink, Chicken Dum Biriyani, Onion Raita, Chicken Gravy, Boiled Egg, Chicke',
       'Schezwan Prawn', 'Kozhithoran (Roasted Chicken With Coconut)',
       'Kumpo Prawns', 'Kumpo Fish Dry', 'Mutton Dum Biriyani',
       'Schewan Fried Rice', 'Sambar Sadham',
       'Pepper Grill Chicken ( Quater )', 'Tandoor Chicken Quater',
       'Veg Pulao', 'Ygr Special Chicken', 'American Chopsey( Veg)',
       'Lessi Sweet', 'Goli Soda', 'Lessi Salt', 'Chicken Tikka',
       'Nethili Fish Fry', 'Chilly Gravy (Babycorn)',
       'Chicken Malai Kebab'], dtype=object)

In [ ]:
df["Item Name"].nunique()

249

In [ ]:
df.isnull().sum()

Date              0
Timestamp         0
Invoice No.       0
Item Name         0
Price             0
Qty.              0
Sub Total         0
Discount          0
Tax               0
Final Total       0
Table No.         0
Server Name       0
Covers            0
Variation      7234
Category          0
HSN            7242
dtype: int64

In [ ]:
df["Final Total"].sum()

1208136.5899999999

In [ ]:
df["Final Total"].sum() / df["Invoice No."].nunique()

#average order value = total amount/total orders

549.4027239654388

In [ ]:
df['Category'].unique()

array(['Indian Breads', 'Veg Gravy', 'Veg Starters',
       'Deserts & Mocktails', 'NON VEG STARTERS FISH',
       'NON VEG STARTERS CHICKEN', 'NON VEG BRIYANI & RICE',
       'VEG BIRYANI & RICE', 'Non Veg Gravy', 'Non Veg Soup',
       'NON VEG STARTERS EGG', 'Non Veg Tandoor', 'Veg Soup',
       'Non Veg combos', 'NON VEG STARTERS MUTTON'], dtype=object)

In [ ]:
df['Discount'].sum()

10438.77

In [ ]:
df['Tax'].sum()

57532.36

In [ ]:
df['Tax'].sum() / df["Invoice No."].nunique()

26.162964984083676

In [ ]:
df['Discount'].sum() / df['Invoice No.'].nunique()

4.747053206002729